import { CacheableResponsePlugin } from 'workbox-cacheable-response';
import { ExpirationPlugin } from 'workbox-expiration';
import { precacheAndRoute } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { CacheFirst, NetworkFirst, StaleWhileRevalidate } from 'workbox-strategies';

// Precache all assets generated by build process
precacheAndRoute(self.__WB_MANIFEST);

const CACHE_NAME = 'radiantai-v1'
const OFFLINE_URL = './offline.html'

// Essential files to cache for manual tracking if needed (optional since precacheAndRoute handles build assets)
const urlsToCache = [
  '/',
  './offline.html',
  '/manifest.json',
  '/favicon_io/android-chrome-192x192.png',
  '/favicon_io/android-chrome-512x512.png',
]

// Runtime Caching for API
registerRoute(
  ({ url }) => url.origin.includes('api'),
  new NetworkFirst({
    cacheName: 'api-cache',
    plugins: [
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
      new ExpirationPlugin({
        maxEntries: 50,
        maxAgeSeconds: 60 * 60 * 24, // 24 hours
      }),
    ],
  })
);

// Install event - still kept for manual offline.html caching if not in manifest
self.addEventListener('install', (event) => {
  console.log('[Service Worker] Install')
  event.waitUntil(
    caches.open(CACHE_NAME).then((cache) => cache.addAll(urlsToCache))
  )
  self.skipWaiting()
})

// Activate event
self.addEventListener('activate', (event) => {
  console.log('[Service Worker] Activate')
  event.waitUntil(
    caches.keys().then((cacheNames) => {
      return Promise.all(
        cacheNames.map((cacheName) => {
          if (cacheName !== CACHE_NAME && !cacheName.startsWith('workbox-precache')) {
            return caches.delete(cacheName);
          }
        })
      );
    })
  );
  return self.clients.claim()
})

// Custom Fetch for Offline Page Fallback (if not handled by workbox)
self.addEventListener('fetch', (event) => {
  if (event.request.mode === 'navigate') {
    event.respondWith(
      fetch(event.request).catch(() => caches.match(OFFLINE_URL))
    );
  }
});

// Handle messages from client
self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting()
  }
})

// Handle rich push notifications
self.addEventListener('push', (event) => {
  console.log('[Service Worker] Push received')

  if (!event.data) {
    console.warn('[Service Worker] Push event with no data')
    return
  }

  try {
    const data = event.data.json()
    console.log('[Service Worker] Push payload:', data)

    const title = data.title || 'RadiantAI'
    const options = {
      body: data.body || 'New update from RadiantAI',
      icon: data.icon || '/favicon_io/android-chrome-192x192.png',
      badge: data.badge || '/favicon_io/android-chrome-192x192.png',
      image: data.image || null,
      vibrate: data.vibrate || [200, 100, 200],
      tag: data.tag || 'radiantai-notification',
      renotify: true,
      requireInteraction: data.requireInteraction || false,
      actions: data.actions || [],
      data: {
        url: data.data?.url || '/dashboard',
        notificationId: data.data?.notificationId,
        timestamp: Date.now(),
      },
    }

    event.waitUntil(self.registration.showNotification(title, options))
  } catch (err) {
    console.error('[Service Worker] Error parsing push data:', err)
    // Fallback if data is not JSON
    const text = event.data.text()
    event.waitUntil(
      self.registration.showNotification('RadiantAI', {
        body: text,
        icon: '/favicon_io/android-chrome-192x192.png',
        badge: '/favicon_io/android-chrome-192x192.png',
      })
    )
  }
})

// Handle notification clicks
self.addEventListener('notificationclick', (event) => {
  console.log('[Service Worker] Notification clicked')

  const notification = event.notification
  const action = event.action
  const urlToOpen = notification.data?.url || '/dashboard'

  notification.close()

  if (action === 'dismiss') {
    return
  }

  // Deep linking logic
  event.waitUntil(
    clients
      .matchAll({
        type: 'window',
        includeUncontrolled: true,
      })
      .then((windowClients) => {
        // Check if there's already a tab open with this URL
        for (let i = 0; i < windowClients.length; i++) {
          const client = windowClients[i]
          if (client.url === urlToOpen && 'focus' in client) {
            return client.focus()
          }
        }
        // If no tab is open, open a new one
        if (clients.openWindow) {
          return clients.openWindow(urlToOpen)
        }
      })
  )

  // Notify clients about the click (for analytics or state updates)
  event.waitUntil(
    clients.matchAll().then((matchedClients) => {
      matchedClients.forEach((client) => {
        client.postMessage({
          type: 'NOTIFICATION_CLICKED',
          notificationId: notification.data?.notificationId,
          action,
        })
      })
    })
  )
})

console.log(
  '[Service Worker] Loaded - Enhanced version for rich notifications'
)
